apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: test
spec:
  project: default
  source:
    repoURL: https://github.com/MasterixGM/Test-Istio
    path: apps
    targetRevision: HEAD
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: false
      selfHeal: true