apiVersion: v1
kind: Namespace
metadata:
  name: istio-cni
  annotations:
    argocd.argoproj.io/sync-wave: "5"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cni
  namespace: istio-cni
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: https://newrepo.com/new-org/new-repo.git
    path: apps
    targetRevision: HEAD
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---      
apiVersion: sailoperator.io/v1alpha1
kind: IstioCNI
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  namespace: istio-cni
  version: v1.24.1