apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: https://github.com/MasterixGM/Test-Istio
    path: apps
    targetRevision: HEAD
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Istio
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  version: v${ISTIO_VERSION}
  namespace: istio-system
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster2
      network: network2
