apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-service-mesh-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/MasterixGM/Test-Istio
    path: apps
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: service-mesh
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-mesh-operator
  namespace: service-mesh
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-mesh-operator
  template:
    metadata:
      labels:
        app: service-mesh-operator
    spec:
      containers:
        - name: service-mesh-operator
          image: newrepo/service-mesh-operator:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-mesh-operator
  namespace: service-mesh
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  selector:
    app: service-mesh-operator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080